# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

aetherconstruct_version=1.20.1-0.0.1

mc_version=1.20.1

forge_version=47.2.6
curio_version=5.9.1
tcon_version=3.10.0.67
mantle_version=1.11.55
cofh_core_version=11.0.5.23
# aether
aether_version=1.5.1-neoforge
nitrogen_version=1.20.1-1.0.11-neoforge
cumulus_version=1.20.1-1.0.1-neoforge
treasure_reforging_version=1.20.1-1.0.1-neoforge
jei_version=15.20.+